- type: replace
  path: /instance_groups/name=terraform-secure-backend/jobs/-
  value:
    name: route_registrar
    release: routing
    consumes:
      nats:
        from: nats
        deployment: ((cf_deployment_name))
    properties:
      route_registrar:
        routes:
          - name: terraform-secure-backend
            registration_interval: 20s
            server_cert_domain_san: "tsb.service.cf.internal"
            tls_port: 8081
            uris:
              - tsb.((system_domain))

- type: replace
  path: /releases/-
  value:
    name: routing
    url: https://bosh.io/d/github.com/cloudfoundry-incubator/cf-routing-release?v=0.184.0
    version: 0.184.0
    sha1: f35eb9884e1c097ff21843e6f2d0eebd22ac2073